### ISSUE TITLE
Issue with version 4.1.1

### ISSUE THREAD

**Issue by brunowego** [Narzerus/angular-permission#346]
After update to version 4.1.1 I get the error bellow:

``` sh
TypeError: i[r].validationFunction.indexOf is not a function
    at http://app.sistemamais.com.br/main.d8eb1933d403ee234700.bundle.js:15:16333
    at Object.r [as forEach] (http://app.sistemamais.com.br/main.d8eb1933d403ee234700.bundle.js:5:24003)
    at e.t (http://app.sistemamais.com.br/main.d8eb1933d403ee234700.bundle.js:15:16173)
    at http://app.sistemamais.com.br/main.d8eb1933d403ee234700.bundle.js:15:13949
    at Object.a [as invoke] (http://app.sistemamais.com.br/main.d8eb1933d403ee234700.bundle.js:6:11955)
    at i.validatePermission (http://app.sistemamais.com.br/main.d8eb1933d403ee234700.bundle.js:1:15940)
    at http://app.sistemamais.com.br/main.d8eb1933d403ee234700.bundle.js:1:20541
    at Array.map (native)
    at s.resolvePropertyValidity (http://app.sistemamais.com.br/main.d8eb1933d403ee234700.bundle.js:1:20368)
    at i (http://app.sistemamais.com.br/main.d8eb1933d403ee234700.bundle.js:1:19143)
```

Its happen when uglify with webpack. If return to version 4.0.6 works perfectly. Thanks.

**Comment by masterspambot** [comment]
Could prove more information eg. on exact which function webpack has problem? Because I can not see usage of `validationFunction.indexOf` in the code and mapping is bundled, so stack gives me no info to inspect the issue.

**Comment by AlainD-** [comment]
I've got that same error too after upgrading from v3.2.1 to 4.1.1. My service is:
```javaScript
        function hasPermission(permission) {
            var deferred = $q.defer();
            var hasPermission = false;

            // check if user has permission via its roles
            angular.forEach(currentUser.roles, function(role) {
                // check role exists
                if(RoleStore.hasRoleDefinition(role)) {
                    // get the role
                    var roles = RoleStore.getStore();

                    if(angular.isDefined(roles[role])) {
                        // check if the permission we are validating is in this role's permissions
                        if(-1 !== roles[role].validationFunction.indexOf(permission)) {//<-- this line causes the error!
                            hasPermission = true;
                        }
                    }
                }
            });

            // if we have permission resolve otherwise reject the promise
            if(hasPermission) {
                deferred.resolve();
            }
            else {
                deferred.reject();
            }

            // return promise
            return deferred.promise;
        }
```

which is called when defining the permissions:
```javaScript
            PermPermissionStore.defineManyPermissions(permissions, function (permissionName) {
                return UserService.hasPermission(permissionName);
            });
```

But I can't figure out what the problem now is with the new version of angular-permission, or what I need to update in my code to make it compatible. It must be something not documented in the wiki in the section upgrade 3.x to 4.x...

Thank you in advance for you help.

**Comment by AlainD-** [comment]
Repying to myself:

OK, I think I understand why this is happening. Before, in v3.2.1 the constructor: `function Role(roleName, validationFunction) {...}`
could return an `Array` if the `validationFunction`parameter was defined as an array:
`this.validationFunction = validationFunction;`


But now in v4.1.1, we have `this.validationFunction = annotateValidationFunction(validationFunction);`which now returns a `Function` no matter what type of the parameter of the constructor. Moreover, that function seems to be a promise.

So, in my service, if I use instead: `roles[roleName].validationFunction().then(...)`, I get a too many recursion error. Now I'm stuck! :-/

Some help to make us see clear would be much appreciated :-)

**Comment by AlainD-** [comment]
OK.... progressing. In 3.2.1, we could just use the validationFunction which contained the list of permissions defined for the role (when all the roles where defined with an array of permissionNames). But in 4.1.1 we now use`preparePermissionEvaluation` which basically uses the validationFunction of the permission to say Valid or Invalid. Which is completely different now. The scope of the property `validationFunction` of the Role changed. What we are doing in our code is the following:
1.  to validate a permission, check if the user has a role
2.  for that role check if all its permissions are valid (new implementation of `validationFunction`/`preparePermissionEvaluation`)
3.  but for that validate a permission as defined in 1. above => oops infinite loop!

We can no longer get the list of permissions belonging to a role through the role definition. I don't know if the developpers will provide us with a method or a way of getting that ? Or even better a way of checking if a given roleName is part of the one role definition ?

Thanks.

**Comment by AlainD-** [comment]
So, temporary solution for me at the moment (because it only works when all the roles are defined with an array of permission names):

- create a `PermissionService` where I define my permissions array, and my roleMap object
- Inject that service in my permission.run so that I know have
```javaScript
PermRoleStore.defineManyRoles(PermissionService.roleMap);

PermPermissionStore.defineManyPermissions(PermissionService.permissions,/*@ngInject*/ function (permissionName, transitionProperties) {
    return UserService.hasPermission(permissionName);
});
```
And in my validation function:
```javaScript
function hasPermission(permission) {
    var deferred = $q.defer();
    var hasPermission = false;

    // check if user has permission via its roles
    angular.forEach(currentUser.roles, function(role) {
        // check role exists
        if(RoleStore.hasRoleDefinition(role)) {
            // get the role
            var roles = PermissionService.roleMap;//RoleStore.getStore();

            if(angular.isDefined(roles[role])) {
                // check if the permission we are validating is in this role's permissions
                if(-1 !== roles[role]/*.validationFunction*/.indexOf(permission)) {
                    hasPermission = true;
                }
            }
        }
    });

    // if we have permission resolve otherwise reject the promise
    if(hasPermission) {
        deferred.resolve();
    }
    else {
        deferred.reject();
    }

    // return promise
    return deferred.promise;
}
```

**Comment by masterspambot** [comment]
Gonna fix that ASAP.

**Comment by masterspambot** [comment]
I just went through the code @AlainD- has written as a workaround. As you are calling internals of angular-permission lib there is nothing to fix as the solution here `roles[role]/*.validationFunction*/.indexOf(permission)` is working and is proper context aware call. It is expected behavior affecting internal code. 

And more personal question @AlainD- why do you have to check for existence of validationFunction if `hasRoleDefinition` returns you info that role is defined?

**Comment by AlainD-** [comment]
@masterspambot I don't really need to check the existence of `validationFunction`. What I need is a way of saying if a user which has a given role has a specific permission.

Let me explain: I have an application client-server.

The **server** handles a list of users. These users are assigned a list of roles. Let say a user `User01` is `ROLE_ADMIN` and `ROLE_EDITOR`:
```json
{
    "username": "user01",
    "name": "User01",
    "roles": ["ROLE_ADMIN", "ROLE_EDITOR"]
}
```

In the **client**, my angularjs application, I defined a `roleStore` and a `permissionStore`. Let says for instance
```json
{
    "ROLE_ADMIN": ["canCreateUser", "canUpdateUser"],
    "ROLE_EDITOR": ["canEditPage", "canEditSection"],
    "ROLE_VALIDATOR": ["canValidateThis", "canValidateThat"]
}
```
Those permissions are only used for the front-end (client).

Now if I create a section in the front-end which is restricted to `permission-only="canEditSection"`, it is natural to define the validation of the store by using a method to check if the user has this permission. Since the backend does not know anything about the permissions of the front-end, I need to know if among the permission store defined, a certain role (one of the user's) has the permission 'canEditSection'.

So as you see, the validation is not just checking the existence of the roleDefinition, or the existence of the permission definition, but it is to know if the permission is associated to a given/named role. Before v4.x `validationFunction` seemed to provide us with that mapping, but since v4.x this info seems to be missing. It like we can only check if the permission definition exists or the role definition exists, and that's it. Or did I misunderstand something?

**Comment by brunowego** [comment]
Only works with version 4.0.6 the follow settings:

```js
# permissions.run.js
const PermissionsRun = (PermPermissionStore, PermRoleStore, AuthService, $state, $rootScope) => {
  'ngInject';

  let permissions = [
    'dashboard', 'disputes', 'remittances', ...
  ];

  PermPermissionStore.defineManyPermissions(permissions, (permissionName) => {
    return AuthService.hasPermission(permissionName);
  });

  PermRoleStore.defineManyRoles({
    'SUPERVISOR': ['dashboard', 'disputes', 'remittances'],
    'GUEST': ['dashboard', 'disputes']
  });

  const deniedHandle = $rootScope.$on('$stateChangePermissionDenied', () => $state.go('auth.login'));

  $rootScope.$on('$destroy', () => {
    deniedHandle();
  });
};

export default PermissionsRun;
```

```js
# auth.service.js
import angular from 'angular';

class AuthService {
  ...

  hasPermission(permission) {
    let deferred = this.$q.defer();
    let hasPermission = false;

    // Check if user has permission via its roles.
    angular.forEach(this.currentUser().roles, (role) => {
      // Check role exists.
      if (this.role.hasRoleDefinition(role)) {
        let roles = this.role.getStore();

        if (angular.isDefined(roles[role])) {
          // Check if the permission we are validating is in this role's permissions.
          if (-1 !== roles[role].validationFunction.indexOf(permission)) {
            hasPermission = true;
          }
        }
      }
    });

    // If we have permission resolve otherwise reject the promise.
    if (hasPermission) {
      deferred.resolve();
    } else {
      deferred.reject();
    }

    return deferred.promise;
  }

  ...
}
```

@AlainD- did you use the latest version?

**Comment by PhillyOne** [comment]
The migration documentation indicates that nothing major needs to be done in order to move from 3.x to 4.x and 4.x to 5.x yet since upgrading to the latest version, I can no longer get this to work and my application is broken. 

@masterspambot The above is a genuine use case, yet we find ourselves hunting through stackoverflow and the issues to find out how to do it properly. I have only been forced to upgrade due to an update on my dependencies and now permissions no longer work correctly.

What is the correct way to do the above in 5.x? Also, permission-only in views no longer seems to work in 5.x when doing something like the above. Can you please help.

**Comment by PhillyOne** [comment]
@brunowego The above also works for me in 4.0.6, I am sticking with this version until this is fixed.
